[package]
name = "log4r"
authors = ["Wouter Pennings"]
version = "0.1.0"
edition = "2021"
description = "Stupidly simple logging utils"
documentation = "https://docs.rs/log4r"
license = "MIT"
repository = "https://github.com/WouterPennings/logr"

[dependencies]
